"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { KeyRound, UserPlus } from "lucide-react";
import { useAuth } from "@/lib/auth-context";

type SignupMode = "owner" | "invite";

export default function SignupPage() {
  const router = useRouter();
  const { signup } = useAuth();
  const [mode, setMode] = useState<SignupMode>("owner");
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [inviteCode, setInviteCode] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const invite = params.get("invite")?.trim();
    if (!invite) return;
    setMode("invite");
    setInviteCode(invite);
  }, []);

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError("");
    setMessage("");

    const code = inviteCode.trim();
    const displayName = name.trim();
    if (!displayName) {
      setError("Enter your name.");
      return;
    }
    if (mode === "invite" && !code) {
      setError("Enter the invite code generated by the workspace owner.");
      return;
    }

    setIsSubmitting(true);
    try {
      const response = await signup(displayName, email, password, undefined, mode === "invite" ? code : undefined);
      if (response.status === "active") {
        setMessage(response.message || "Invite accepted. You can now log in.");
        return;
      }
      if (response.status === "pending_verification") {
        setMessage(
          mode === "invite"
            ? "Invite accepted. You can now log in."
            : response.message || "Owner account created. Check your email to verify your account, then log in."
        );
        return;
      }
    } catch (err) {
      const text = err instanceof Error ? err.message : "Unable to create the account.";
      setError(text.includes("already exists") ? `${text} Log in with this email, then accept the invite code.` : text);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <main className="auth-shell">
      <section className="auth-card">
        <Link className="brand" href="/">
          <span className="brand-mark">
            {mode === "invite" ? <KeyRound size={18} aria-hidden="true" /> : <UserPlus size={18} aria-hidden="true" />}
          </span>
          CreditFlow
        </Link>
        <h1>Create your account</h1>
        <p>Choose whether you are creating a workspace as an owner or joining a workspace with an invite code.</p>

        <div className="auth-mode-toggle" role="tablist" aria-label="Signup type">
          <button className={mode === "owner" ? "active" : ""} type="button" onClick={() => setMode("owner")} role="tab" aria-selected={mode === "owner"}>
            Sign up
          </button>
          <button className={mode === "invite" ? "active" : ""} type="button" onClick={() => setMode("invite")} role="tab" aria-selected={mode === "invite"}>
            Accept an invite
          </button>
        </div>

        <div className="notice">
          {mode === "owner"
            ? "This creates your account as the workspace Owner after email verification."
            : "Enter the invite code/token generated by the workspace Owner. The invite must match this email address; invited members do not need email verification."}
        </div>

        <form className="form-grid with-top-gap" onSubmit={handleSubmit} noValidate>
          {mode === "invite" ? (
            <div className="field">
              <label htmlFor="invite-code">Invite code or token</label>
              <input id="invite-code" value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} placeholder="Paste owner-generated invite code" required />
            </div>
          ) : null}
          <div className="field">
            <label htmlFor="name">Name</label>
            <input id="name" type="text" autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Your full name" required />
          </div>
          <div className="field">
            <label htmlFor="email">Email</label>
            <input id="email" type="email" autoComplete="username" value={email} onChange={(event) => setEmail(event.target.value)} required />
          </div>
          <div className="field">
            <label htmlFor="password">Password</label>
            <input id="password" type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} required />
          </div>
          {error ? <div className="danger-note">{error}</div> : null}
          {message ? <div className="success-note">{message}</div> : null}
          <div className="auth-inline-action">
            <Link className="link" href="/forgot-password">Forgot password?</Link>
          </div>
          <button className="button primary" type="submit" disabled={isSubmitting}>
            {isSubmitting ? "Creating account..." : mode === "invite" ? "Accept invite and create account" : "Create owner account"}
          </button>
        </form>
        <p>
          Already verified?{" "}
          <Link className="link" href="/login">
            Log in
          </Link>
        </p>
      </section>
    </main>
  );
}


